[package]
name = "lta_utils_commons"
version = "0.2.0"
authors = ["budinverse <budisyahiddin@gmail.com>"]
edition = "2018"
license = "MIT"
description = "ğŸšUtils for lta-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.0", features = ["json", "blocking"]}
serde = { version = "1.0.97", features = ["derive"] }
lazy_static = "1.3.0"
serde_json = "1.0.40"
regex = "1.3.0"
chrono = { version = "0.4.7", features = ["serde"] }