[package]
name = "lta_blocking"
version = "0.1.0"
authors = ["budinverse <budisyahiddin@gmail.com>"]
edition = "2018"
license = "MIT"
description = "ğŸšBlocking requests for lta-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lta_utils_commons = "0.1.0"
lta_models = "0.1.0"